### ISSUE TITLE
Which formats can be converted to?

### ISSUE THREAD

**Issue by eahogue** [akb89/pyfn#25]
Hello,

The readme says:

```
"pyfn can be used to:

convert data to and from FRAMENET XML, SEMEVAL XML, SEMAFOR CoNLL, BIOS and CoNLL-X"
```

But after this, CONLL-X is not mentioned. I do not see an option for this in the code, either.

I need to convert to a standard CONLL format so that I can match it to another dataset in another CONLL format. CONLL-X would work for this purpose.* Is there actually a way to convert to this format, or is the readme in error?

* I don't think I can use SEMAFOR CONLL because I need a standard CONLL to use a standard CONLL converter to match them. So, unless SEMAFOR CONLL conforms exactly to a standard CONLL format (e.g., CONLL-05, CONLL-12, CONLL-X, CONLL-U), it will not work. If "SEMAFOR CONLL" _is_ just another name for one of these, can someone kindly inform we which one?

Thank you!
Alan

Additional:

After trying a conversion to semafor conll format, I have get this:

`dev.frames            dev.sentences         test.frames           test.sentences        train.frame.elements  train.sentences`

x.sentences files are just the raw text sentences. Like so:

```
" 'The true voodoo-worshipper attempts nothing of importance without certain sacrifices which are intended to propitiate his unclean gods .
" A chaotic case , my dear Watson , " said Holmes over an evening pipe .
" A lamb , I should say , or a kid . "
```

the x.frames files contain only frame information, no frame element info:

```1       0.0     1       Quantified_mass many.a  12      many    1232
1       0.0     1       Stimulus_focus  nice.a  13      nice    1232
1       0.0     1       Buildings       pub.n   14      pubs    1232
1       0.0     1       Education_teaching      teach.v 3       taught  1233
```

For the dev and test sets, this is all the information contained in these files. IOW, where is the frame element data for the test and dev splits? Am I confused? Is this info somewhere else?

Thanks again,
Alan

**Comment by akb89** [comment]
Hi Alan!

Thank you for your interest in pyfn! 

What exactly do you need the CONLL format for? Do you expect to find FrameNet annotation there? If so that is not possible (at least with pyfn): the only "CONLL-like" format in pyfn that contains FrameNet annotation is the "SEMAFOR CONLL" format. 

CONLL-x with pyfn is only used by (and as output of) POS taggers and dependency parsers. More details [here](https://github.com/akb89/pyfn/blob/master/FORMAT.md) under "SEMAFOR CoNLL". 

At which step of the process would you need CONLL-x files? 

Also, frame element data for the dev and test splits are generated by the decoder using the bash scripts. For instance, for SEMAFOR, those files would be generated using `./semafor.sh -m decode -x 001 -s test` (but only after preprocessing, preparation and training, see the README under `semafor.sh` for instance). 
If you're looking for gold frame element data, those are kept in xml format for scoring (more details under the [scripts/score.sh](https://github.com/akb89/pyfn/blob/master/scripts/score.sh) file). 

Hope this helps, let me know if not. 

Cheers,

Alex

**Comment by eahogue** [comment]
Thanks for getting back to me.

My apologies, I thought CONLL-X was usable for frame parsing. Maybe my use case is outside of the scope of pyfn. 

It looks like the following CONLL formats have been used for frame semantic parsing shared tasks:

CONLL-04
CONLL-05
CONLL-09
CONLL-12

My problem is that I want to use framenet data together with propbank data and semlink mappings. The latter is available in CONLL-12 format, I believe. So if I can convert framenet data to let's say for example CONLL-09, then I can easily, from there, convert between CONLL-09 and CONLL-12 using another tool. That would be really useful because all of my data would then be in the same format.

Unfortunately, AFAICT, SEMAFOR CONLL is not an official, recognized CONLL format. I have been searching for info on this to no avail so far. If it turns out that SEMAFOR CONLL is actually just a standard CONLL format by another name, then if I can figure out what that name is, I can convert it to whichever CONLL I need.

**Comment by akb89** [comment]
Would you be able to give me an example of what you would expect framenet data to look like in CONLL-09 (or whatever format you'd prefer)? 
Although it is not currently supported, it shouldn't be too much work to add it. If you give me the specs, I can take a look at it and see what I can do.
